create database company;
use company;
CREATE TABLE DEPARTMENT
(DNO VARCHAR (20) PRIMARY KEY,
 DNAME VARCHAR (20),
MGRSTARTDATE DATE);
CREATE TABLE EMPLOYEE (
    SSN VARCHAR(20) PRIMARY KEY,
    FNAME VARCHAR(20),
    LNAME VARCHAR(20),
    ADDRESS VARCHAR(20),
    SEX CHAR(1),
    SALARY INTEGER,
    SUPERSSN VARCHAR(20),
    DNO VARCHAR(20),
    FOREIGN KEY (SUPERSSN) REFERENCES EMPLOYEE(SSN),
    FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNO)
);
ALTER TABLE DEPARTMENT
ADD MGRSSN VARCHAR(20) REFERENCES EMPLOYEE (SSN);

INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX, SALARY)
VALUES ('RNSECE01', 'JOHN', 'SCOTT', 'BANGALORE', 'M', 450000);

INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX, SALARY)
VALUES ('RNSCSE01', 'JAMES', 'SMITH', 'BANGALORE', 'M', 500000);

INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX, SALARY)
VALUES ('RNSCSE02', 'HEARN', 'BAKER', 'BANGALORE', 'M', 700000);

INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX, SALARY)
VALUES ('RNSCSE03', 'EDWARD', 'SCOTT', 'MYSORE', 'M', 500000);

INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX, SALARY)
VALUES ('RNSCSE04', 'PAVAN', 'HEGDE', 'MANGALORE', 'M', 650000);

INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX, SALARY)
VALUES ('RNSCSE05', 'GIRISH', 'MALYA', 'MYSORE', 'M', 450000);

INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX, SALARY)
VALUES ('RNSCSE06', 'NEHA', 'SN', 'BANGALORE', 'F', 800000);

INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX, SALARY)
VALUES ('RNSACC01', 'AHANA', 'K', 'MANGALORE', 'F', 350000);


INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX, SALARY)
VALUES ('RNSACC02', 'SANTHOSH', 'KUMAR', 'MANGALORE', 'M', 300000);

INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX, SALARY)
VALUES ('RNSISE01', 'VEENA', 'M', 'MYSORE', 'M', 600000);

INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX, SALARY)
VALUES ('RNSIT01', 'NAGESH', 'HR', 'BANGALORE', 'M', 500000);



INSERT INTO DEPARTMENT VALUES ('1', 'ACCOUNTS', '2001-01-01', 'RNSACC02');

INSERT INTO DEPARTMENT VALUES ('2', 'IT', '2016-08-01', 'RNSIT01');

INSERT INTO DEPARTMENT VALUES ('3', 'ECE', '2008-06-01', 'RNSECE01');

INSERT INTO DEPARTMENT VALUES ('4', 'ISE', '2015-08-01', 'RNSISE01');

INSERT INTO DEPARTMENT VALUES ('5', 'CSE', '2002-06-01', 'RNSCSE05');


select*from employee;
select*from department;

UPDATE EMPLOYEE SET DNO='5', SUPERSSN='RNSCSE06' WHERE
SSN='RNSCSE05';

DELETE FROM EMPLOYEE WHERE DNO=1 limit 1;

DROP TABLE EMPLOYEE;
DROP TABLE department;

CREATE TABLE DEPT(DEPTNO INTEGER, DNAME VARCHAR(10),LOC
VARCHAR(4), PRIMARY KEY(DEPTNO));

ALTER TABLE DEPT RENAME TO DEPARTMENT;

ALTER TABLE DEPARTMENT
ADD COLUMN PINCODE INT(6) NOT NULL;

ALTER TABLE DEPARTMENT DROP COLUMN LOC CASCADE;

ALTER TABLE DEPARTMENT RENAME COLUMN DNAME TO DEPT_NAME;

ALTER TABLE DEPARTMENT
ADD COLUMN loc INT(6) NOT NULL;

ALTER TABLE DEPARTMENT MODIFY LOC CHAR(10);

DROP TABLE DEPARTMENT;

select*from department;



CREATE TABLE EMPLOYEE (
    EMPNO VARCHAR(5) PRIMARY KEY,
    EMP_NAME VARCHAR(50),
    DEPT VARCHAR(50),
    SALARY INT,
    DOJ DATE,
    BRANCH VARCHAR(50)
);

INSERT INTO EMPLOYEE (EMPNO, EMP_NAME, DEPT, SALARY, DOJ, BRANCH)
VALUES 
('E101', 'Amit', 'Production', 45000, '2000-03-12', 'Bangalore'),
('E102', 'Amit', 'HR', 70000, '2002-07-03', 'Bangalore'),
('E103', 'Sunita', 'Management', 120000, '2001-01-11', 'Mysore'),
('E105', 'Sunita', 'IT', 67000, '2001-08-01', 'Mysore'),
('E106', 'Mahesh', 'Civil', 145000, '2003-09-20', 'Mumbai');

select * from employee;

SELECT EMPNO, SALARY FROM EMPLOYEE;
select avg(salary) from employee;
select count(*) from employee;
select count(DISTINCT emp_name) from employee;
SELECT EMP_NAME, SUM(SALARY) AS TotalSalary, COUNT(*) AS EmployeeCount
FROM EMPLOYEE
GROUP BY EMP_NAME;
SELECT EMP_NAME, SUM(SALARY) FROM EMPLOYEE
GROUP BY(EMP_NAME)
HAVING SUM(SALARY)>120000;

select emp_name from employee
order by emp_name desc;

select * from employee
where emp_name='Amit' and salary>50000;










