CREATE TABLE DEPARTMENT
(DNO VARCHAR (20) PRIMARY KEY, DNAME VARCHAR(20),
MGRSTARTDATE DATE);
CREATE TABLE EMPLOYEE
(SSN VARCHAR (20) PRIMARY KEY, FNAME VARCHAR (20),
LNAME VARCHAR (20),
ADDRESS VARCHAR (20),
SEX CHAR (1),
SALARY INTEGER,
SUPERSSN REFERENCES EMPLOYEE (SSN),
 DNO REFERENCES DEPARTMENT (DNO));
 
 ALTER TABLE DEPARTMENT
ADD MGRSSN REFERENCES EMPLOYEE (SSN);

INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX,
SALARY) VALUES ( ̳RNSECE01‘,‘JOHN‘,‘SCOTT‘,‘BANGALORE‘,‘M‘,
450000); INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS,
SEX, SALARY) VALUES
( ̳RNSCSE01‘,‘JAMES‘,‘SMITH‘,‘BANGALORE‘,‘M‘, 500000); INSERT
INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX, SALARY)
VALUES ( ̳RNSCSE02‘,‘HEARN‘,‘BAKER‘,‘BANGALORE‘,‘M‘,
700000); INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS,
SEX, SALARY) VALUES
( ̳RNSCSE03‘,‘EDWARD‘,‘SCOTT‘,‘MYSORE‘,‘M‘, 500000);
INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX,
SALARY) VALUES
( ̳RNSCSE04‘,‘PAVAN‘,‘HEGDE‘,‘MANGALORE‘,‘M‘, 650000); INSERT
INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX, SALARY)
VALUES ( ̳RNSCSE05‘,‘GIRISH‘,‘MALYA‘,‘MYSORE‘,‘M‘, 450000);
INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX,
SALARY) VALUES ( ̳RNSCSE06‘,‘NEHA‘,‘SN‘,‘BANGALORE‘,‘F‘,
800000);
INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX,
SALARY) VALUES ( ̳RNSACC01‘,‘AHANA‘,‘K‘,‘MANGALORE‘,‘F‘,
350000);
INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX,
SALARY) VALUES
( ̳RNSACC02‘,‘SANTHOSH‘,‘KUMAR‘,‘MANGALORE‘,‘M‘, 300000);
INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX,
SALARY) VALUES ( ̳RNSISE01‘,‘VEENA‘,‘M‘,‘MYSORE‘,‘M‘, 600000);
INSERT INTO EMPLOYEE (SSN, FNAME, LNAME, ADDRESS, SEX,
SALARY) VALUES ( ̳RNSIT01‘,‘NAGESH‘,‘HR‘,‘BANGALORE‘,‘M‘,
500000);

INSERT INTO DEPARTMENT VALUES ( ̳1‘,‘ACCOUNTS‘,‘01-JAN-
01‘,‘RNSACC02‘);

INSERT INTO DEPARTMENT VALUES ( ̳2‘,‘IT‘,‘01-AUG-
16‘,‘RNSIT01‘);

INSERT INTO DEPARTMENT VALUES ( ̳3‘,‘ECE‘,‘01-JUN-
08‘,‘RNSECE01‘); INSERT INTO DEPARTMENT VALUES ( ̳4‘,‘ISE‘,‘01-

AUG-15‘,‘RNSISE01‘); INSERT INTO DEPARTMENT VALUES
( ̳5‘,‘CSE‘,‘01-JUN-02‘,‘RNSCSE05‘);

UPDATE EMPLOYEE SET DNO=‘5‘, SUPERSSN=‘RNSCSE06‘ WHERE
SSN=‘RNSCSE05‘;

DELETE FROM EMPLOYEE WHERE DNO=1;

The DROP TABLE statement is used to drop an existing table in a database.
DROP TABLE EMPLOYEE;
